version: '3'
services:
  apache:
    image: httpd:latest  # Imagem do Apache
    container_name: apache-container
    volumes:
      - ./app:/usr/local/apache2/htdocs/  # Onde sua aplicação estará
    ports:
      - "8080:80"  # Mapeia a porta 80 do contêiner para a porta 8080 do host
    restart: always
